#!/usr/bin/env bash
set -e

echo "Starting homelab..."

sudo systemctl start docker
sudo systemctl start k3s

cd "$HOME/homelab-ansible"
ansible-playbook -i inventory/hosts.ini site.yml --ask-become-pass

echo "Homelab started"

